### ISSUE TITLE
Valorant 5.12 3D Viewer Error

### ISSUE THREAD

**Issue by jasmurbtw** [4sval/FModel#344]
### Game

Valorant

### Error

```shell
[ERR] System.Exception: Program failed to link with error: Vertex shader(s) failed to link, fragment shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: error(#463) Too many samplers are used in this shader
fragment link error: INVALID_OPERATION.
ERROR: error(#463) Too many samplers are used in this shader

   at FModel.Views.Snooper.Shader..ctor(String name)
```

### Reproduction steps

1. Open the FModel.
2. Open any model (for example "ShooterGame/Content/Equippables/Melee/Alien/Models") in .pak files.
3. Get an error.

Fmodel version 4.4.0.0
Valorant ue4 version 4.26.2.0

**Comment by jasmurbtw** [comment]
> https://www.nvidia.com/content/Control-Panel-Help/vLatest/en-us/mergedProjects/nv3d/Setting_the_Preferred_Graphics_Processor.htm

I have AMD, not NVIDIA:)

**Comment by 4sval** [comment]
> You can change the GPU preference that the OS will use for an application from the Windows Graphics Settings.

**Comment by 4sval** [comment]
Please update us on this case.

You're not the first AMD user to report this kind of behavior but out of 2500+ downloads so far, only a handful of people seem to be getting a fatal shader error. I don't think 95% of these downloads are NVIDIA users.

We already know the problem is because of the textures in our shader. Not supporting [customized UVs](https://docs.unrealengine.com/5.1/en-US/customized-uvs-in-unreal-engine-materials/) will fix the issue but that is a NO-GO for me. Based on [gpuinfo.org](https://opengl.gpuinfo.org/listreports?sortby=date_desc), as long as the GPU is used for FModel, it should work fine.

**Comment by jasmurbtw** [comment]
It didn't help me, so I downloaded the old version (4.3.2.1)

**Comment by 4sval** [comment]
https://cdn.discordapp.com/attachments/765324475498496010/1049363093949522011/FModel.exe

you could also use this fmodel which has customized uvs disabled
